name: Build
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Java And Sbt
        uses: olafurpg/setup-scala@v14
        with:
          java-version: corretto@1.17
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            $HOME/.cache/coursier
            $HOME/.ivy2/cache            
            $HOME/.sbt
          key: ${{ runner.os }}-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Build
        run: sbt build
      - name: Upload To Codecov
        uses: codecov/codecov-action@v5
