name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  build:
    name: Test
    strategy:
      matrix:
        scala:
          - 2.13.10
        java:
          - corretto@1.11
          - corretto@1.19
        os:
          - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Java And Sbt
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            $HOME/.cache/coursier
            $HOME/.ivy2/cache
            $HOME/.sbt/boot/
            $HOME/.sbt            
            target
            project/target
          key: ${{ runner.os }}-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Test (${{ matrix.scala }}, ${{ matrix.java }})
        run: sbt ++${{ matrix.scala }} fullTest
      - name: Upload To Codecov
        uses: codecov/codecov-action@v2
